/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConection.ConexaoBD;
import modeloDao.DaoTatuador;
import modeloBeans.BeansTatuadores;
import modeloBeans.ModeloTabela;


/**
 *
 * @author Gabriel
 */
public class FormTatuador extends javax.swing.JFrame {

    BeansTatuadores mod = new BeansTatuadores();
    DaoTatuador control = new DaoTatuador();
    ConexaoBD conex = new ConexaoBD();
    int flag = 0;
    
    public FormTatuador() {
        setIcon();
        initComponents();
        preencherTabela("select *from tatuadores order by nome_tatuador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtCOD = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxEspecialista = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTempo = new javax.swing.JTextField();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTatuador = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Tatuador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 240, 18);

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 55, 20, 14);

        jtCOD.setEnabled(false);
        getContentPane().add(jtCOD);
        jtCOD.setBounds(39, 52, 48, 20);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(10, 351, 79, 23);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(107, 351, 79, 23);

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(204, 351, 79, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(301, 351, 79, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(398, 351, 79, 23);

        jTextFieldNome.setEnabled(false);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(68, 73, 440, 30);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 86, 35, 14);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Especialista:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 124, 76, 14);

        jComboBoxEspecialista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Old School", "Preto e Cinza", "Lettering ", "Aquarela", "Realismo e Portrait", "Tribal", "Oriental" }));
        jComboBoxEspecialista.setEnabled(false);
        getContentPane().add(jComboBoxEspecialista);
        jComboBoxEspecialista.setBounds(90, 120, 135, 20);

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tempo de Profissão:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(248, 124, 120, 14);

        jTextFieldTempo.setEnabled(false);
        getContentPane().add(jTextFieldTempo);
        jTextFieldTempo.setBounds(378, 121, 130, 30);
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(10, 160, 388, 30);

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisa);
        jButtonPesquisa.setBounds(410, 160, 100, 23);

        jTableTatuador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTatuador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTatuadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTatuador);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 193, 498, 140);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-6, -6, 540, 410);

        setSize(new java.awt.Dimension(545, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo NOME para continuar");
            jTextFieldNome.requestFocus();
        }else if(jTextFieldTempo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo TEMPO DE PROFISSÃO para continuar");
            jTextFieldTempo.requestFocus();
        }else{
  
        if(flag == 1){
            mod.setNome(jTextFieldNome.getText());
            mod.setEspecialidade((String)jComboBoxEspecialista.getSelectedItem());
            mod.setTempoProfissao(jTextFieldTempo.getText());
            control.Salvar(mod);
            jTextFieldNome.setText("");
            jTextFieldTempo.setText("");
            jTextFieldNome.setEnabled(false);
            jTextFieldTempo.setEnabled(false);
            jComboBoxEspecialista.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            preencherTabela("select *from tatuadores order by nome_tatuador");
        }else{
            mod.setCodigo(Integer.parseInt(jtCOD.getText()));
            mod.setNome(jTextFieldNome.getText());
            mod.setEspecialidade((String)jComboBoxEspecialista.getSelectedItem());
            mod.setTempoProfissao(jTextFieldTempo.getText());
            control.editar(mod);
            jtCOD.setText("");
            jTextFieldTempo.setText("");
            jTextFieldNome.setText("");
            jTextFieldNome.setEnabled(false);
            jTextFieldTempo.setEnabled(false);
            jComboBoxEspecialista.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            preencherTabela("select *from tatuadores order by nome_tatuador");
        }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jTextFieldTempo.setEnabled(true);
        jComboBoxEspecialista.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNome.setText("");
        jTextFieldTempo.setText("");
        jTextFieldPesquisa.setText("");
        jtCOD.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setText("");
        jButtonPesquisa.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        mod.setPesquisa(jTextFieldPesquisa.getText());
        BeansTatuadores model = control.buscaTatuadores(mod);
        jtCOD.setText(String.valueOf(model.getCodigo()));
        jTextFieldNome.setText(model.getNome());
        jComboBoxEspecialista.setSelectedItem(model.getEspecialidade());
        jTextFieldTempo.setText(model.getTempoProfissao());
        preencherTabela("Select * from tatuadores where nome_tatuador like '%" + mod.getPesquisa()+"%'");
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setEnabled(!true);
        jTextFieldTempo.setEnabled(!true);
        jComboBoxEspecialista.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisa.setEnabled(true);
        jtCOD.setText("");
        jTextFieldTempo.setText("");
        jTextFieldNome.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldTempo.setEnabled(true);
        jComboBoxEspecialista.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente exlcuir?");
        if(resposta ==JOptionPane.YES_OPTION){
            mod.setCodigo(Integer.parseInt(jtCOD.getText()));
            control.excluir(mod);
            jtCOD.setText("");
            jTextFieldTempo.setText("");
            jTextFieldNome.setText("");
            jTextFieldNome.setEnabled(false);
            jTextFieldTempo.setEnabled(false);
            jComboBoxEspecialista.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jTextFieldPesquisa.setText("");
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            preencherTabela("select *from tatuadores order by nome_tatuador");
        }
     
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableTatuadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTatuadorMouseClicked
        String nome_tatuador =""+jTableTatuador.getValueAt(jTableTatuador.getSelectedRow(), 1);
        conex.getConnection();
        conex.executaSql("select *from tatuadores where nome_tatuador= '"+nome_tatuador+"'");
        try {
            conex.rs.first();
            jtCOD.setText(String.valueOf(conex.rs.getInt("cod_tatuador")));
            jTextFieldNome.setText(conex.rs.getString("nome_tatuador"));
            jComboBoxEspecialista.setSelectedItem(conex.rs.getString("especialidade_tatuador"));
            jTextFieldTempo.setText(conex.rs.getString("tempo_profissao"));
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados"+ex);
        }
        conex.desconecta();
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTableTatuadorMouseClicked

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas  = new String[]{"ID", "Nome","Especialidade", "Tempo de Profissão"};
        conex.getConnection();
        conex.executaSql(Sql);
        
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("cod_tatuador"),conex.rs.getString("nome_tatuador"),conex.rs.getString("especialidade_tatuador"),conex.rs.getString("tempo_profissao")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Busque por outro Tatuador para preencher a tabela");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableTatuador.setModel(modelo);
        jTableTatuador.getColumnModel().getColumn(0).setPreferredWidth(23);
        jTableTatuador.getColumnModel().getColumn(0).setResizable(false);
        jTableTatuador.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableTatuador.getColumnModel().getColumn(1).setResizable(false);
        jTableTatuador.getColumnModel().getColumn(2).setPreferredWidth(180);
        jTableTatuador.getColumnModel().getColumn(2).setResizable(false);
        jTableTatuador.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableTatuador.getColumnModel().getColumn(3).setResizable(false);
        jTableTatuador.getTableHeader().setReorderingAllowed(false);
        jTableTatuador.setAutoResizeMode(jTableTatuador.AUTO_RESIZE_OFF);
        jTableTatuador.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTatuador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEspecialista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTatuador;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldTempo;
    private javax.swing.JTextField jtCOD;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconT.png")));
    }
}
