/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import modeloBeans.BeansAgenda;
import modeloDao.DaoAgenda;

/**
 *
 * @author Gabriel
 */
public class FormAtendimento extends javax.swing.JFrame {
    String cod_agenda;
    BeansAgenda agen = new BeansAgenda();
    DaoAgenda daoAgenda = new DaoAgenda();
    /**
     * Creates new form FormAtendimento
     */
    public FormAtendimento(String codigo) {
        setIcon();
        initComponents();
        cod_agenda=codigo;
        int cod = Integer.parseInt(cod_agenda);
        agen = daoAgenda.BuscarAgendaPorCodigo(cod);
        jTextFieldNome.setText(agen.getNomeCli());
        jFormattedTextFieldNascimento.setText(agen.getClienteNasc());
        jTextFieldDetalhes.setText(agen.getObserva());
        jLabelTatuador.setText(agen.getNomeTatu());
        
    }

    private FormAtendimento() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTatuador = new javax.swing.JLabel();
        jTextFieldTrabFeito = new javax.swing.JTextField();
        jTextFieldObserva = new javax.swing.JTextField();
        jButtonFinalizaAtendimento = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldNascimento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDetalhes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 46, 60, 14);

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tatuador:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 230, 70, 14);

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Trabalho a Realizar:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 250, 180, 14);

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Observação:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 370, 80, 14);

        jLabelTatuador.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabelTatuador.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTatuador.setText("jLabel8");
        getContentPane().add(jLabelTatuador);
        jLabelTatuador.setBounds(90, 230, 194, 14);
        getContentPane().add(jTextFieldTrabFeito);
        jTextFieldTrabFeito.setBounds(10, 270, 524, 75);
        getContentPane().add(jTextFieldObserva);
        jTextFieldObserva.setBounds(110, 360, 420, 30);

        jButtonFinalizaAtendimento.setText("Finaliza Atendimento");
        jButtonFinalizaAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizaAtendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizaAtendimento);
        jButtonFinalizaAtendimento.setBounds(40, 400, 430, 23);

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Formulário de Atendimento");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 10, 310, 23);

        jFormattedTextFieldNascimento.setEnabled(false);
        jFormattedTextFieldNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldNascimento);
        jFormattedTextFieldNascimento.setBounds(480, 60, 120, 30);

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nascimento:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 70, 80, 14);

        jTextFieldNome.setEnabled(false);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(50, 60, 340, 30);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 35, 14);

        jTextFieldDetalhes.setEnabled(false);
        getContentPane().add(jTextFieldDetalhes);
        jTextFieldDetalhes.setBounds(10, 120, 564, 88);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Detalhes:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 70, 14);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-6, 4, 640, 440);

        setSize(new java.awt.Dimension(644, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinalizaAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizaAtendimentoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFinalizaAtendimentoActionPerformed

    private void jFormattedTextFieldNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinalizaAtendimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTatuador;
    private javax.swing.JTextField jTextFieldDetalhes;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldObserva;
    private javax.swing.JTextField jTextFieldTrabFeito;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconT.png")));
    }
}
