/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansClientes;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoCliente;

/**
 *
 * @author Gabriel
 */
public class FormCliente extends javax.swing.JFrame {
    
    ConexaoBD conex = new ConexaoBD();
    BeansClientes cli = new BeansClientes();
    DaoCliente dao = new DaoCliente();
    int flag=0;
    int resposta=0;
    
    
    public FormCliente() {
        setIcon();
        initComponents();
        preencherBairros();
        preencherTabela("select cli_codigo,cli_nome,cli_telefone,cli_rg,bainome from cliente inner join bairro on cli_baicodigo = baicodigo order by cli_nome");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFielCEP = new javax.swing.JFormattedTextField();
        jComboBoxBairro = new javax.swing.JComboBox<>();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldTel = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldNasc = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonAlterar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCodCli = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulário de Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 175, 17);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(21, 346, 552, 92);
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(21, 303, 359, 30);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar);
        jButtonBuscar.setBounds(412, 312, 85, 23);

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Complemento:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 250, 84, 20);

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rua:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(21, 210, 27, 14);

        jTextFieldRua.setEnabled(false);
        getContentPane().add(jTextFieldRua);
        jTextFieldRua.setBounds(52, 205, 280, 30);

        jTextFieldComplemento.setEnabled(false);
        getContentPane().add(jTextFieldComplemento);
        jTextFieldComplemento.setBounds(110, 250, 234, 30);

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CEP:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(336, 210, 24, 14);

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bairro:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 250, 46, 20);

        try {
            jFormattedTextFielCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFielCEP.setEnabled(false);
        getContentPane().add(jFormattedTextFielCEP);
        jFormattedTextFielCEP.setBounds(370, 205, 190, 30);

        jComboBoxBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBairro.setEnabled(false);
        jComboBoxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBairro);
        jComboBoxBairro.setBounds(400, 250, 156, 20);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(433, 449, 85, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(330, 449, 85, 23);

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Endereço");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(21, 185, 58, 14);

        try {
            jFormattedTextFieldTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTel.setEnabled(false);
        getContentPane().add(jFormattedTextFieldTel);
        jFormattedTextFieldTel.setBounds(87, 147, 180, 30);

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(21, 152, 56, 14);

        try {
            jFormattedTextFieldNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNasc.setEnabled(false);
        getContentPane().add(jFormattedTextFieldNasc);
        jFormattedTextFieldNasc.setBounds(331, 109, 152, 30);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nascimento:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(254, 114, 73, 14);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(227, 449, 85, 23);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(124, 449, 85, 23);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(21, 449, 85, 23);

        try {
            jFormattedTextFieldRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRG.setEnabled(false);
        getContentPane().add(jFormattedTextFieldRG);
        jFormattedTextFieldRG.setBounds(44, 109, 200, 30);

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RG:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(21, 114, 19, 14);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(21, 78, 35, 14);

        jTextFieldNome.setEnabled(false);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(60, 73, 452, 30);

        jTextFieldCodCli.setEnabled(false);
        getContentPane().add(jTextFieldCodCli);
        jTextFieldCodCli.setBounds(59, 47, 34, 20);

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cod:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(21, 52, 28, 14);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 610, 530);

        setSize(new java.awt.Dimension(621, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void preencherBairros(){
        conex.getConnection();
        
        conex.executaSql("select *from bairro order by bainome");
        try {
            conex.rs.first();
            jComboBoxBairro.removeAllItems();
            do{
                jComboBoxBairro.addItem(conex.rs.getString("bainome"));
            }while(conex.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher bairros"+ex);
        }
        conex.desconecta();
    }
    
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo NOME para continuar");
            jTextFieldNome.requestFocus();
        }else if(jFormattedTextFieldRG.getText().equals("  .   .   - ")){
            JOptionPane.showMessageDialog(null, "Preencha o campo RG para continuar");
            jFormattedTextFieldRG.requestFocus();
        }else if(jFormattedTextFieldNasc.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null, "Preencha o campo NASCIMENTO para continuar");
            jFormattedTextFieldNasc.requestFocus();
        }else if(jFormattedTextFieldTel.getText().equals("(  )    -    ")){
            JOptionPane.showMessageDialog(null, "Preencha o campo TELEFONE para continuar");
            jFormattedTextFieldTel.requestFocus();    
        }else if(jTextFieldRua.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo RUA para continuar");
            jTextFieldRua.requestFocus(); 
        }else if(jFormattedTextFielCEP.getText().equals("     .   ")){
            JOptionPane.showMessageDialog(null, "Preencha o campo CEP para continuar");
            jFormattedTextFielCEP.requestFocus();  
        }else if(jTextFieldComplemento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo COMPLEMENTO para continuar");
            jTextFieldComplemento.requestFocus(); 
        }else{
            
        if(flag == 1){
            
        cli.setNomeCli(jTextFieldNome.getText());
        cli.setCep(jFormattedTextFielCEP.getText());
        cli.setComplemento(jTextFieldComplemento.getText());
        cli.setNasc(jFormattedTextFieldNasc.getText());
        cli.setRg(jFormattedTextFieldRG.getText());
        cli.setNomeBairro((String) jComboBoxBairro.getSelectedItem());
        cli.setTelefone(jFormattedTextFieldTel.getText());
        cli.setRua(jTextFieldRua.getText());
        dao.Salvar(cli);
        preencherTabela("select cli_codigo,cli_nome,cli_telefone,cli_rg,bainome from cliente inner join bairro on cli_baicodigo = baicodigo order by cli_nome");
        
        jButtonSalvar.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFielCEP.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldTel.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);
        
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!false);
        
        jTextFieldCodCli.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldNome.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFielCEP.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTel.setText("");
        
        }else{
           cli.setNomeCli(jTextFieldNome.getText());
           cli.setCep(jFormattedTextFielCEP.getText());
           cli.setComplemento(jTextFieldComplemento.getText());
           cli.setNasc(jFormattedTextFieldNasc.getText());
           cli.setRg(jFormattedTextFieldRG.getText());
           cli.setNomeBairro((String) jComboBoxBairro.getSelectedItem());
           cli.setTelefone(jFormattedTextFieldTel.getText());
           cli.setRua(jTextFieldRua.getText());
           cli.setCodCli(Integer.parseInt(jTextFieldCodCli.getText()));
           dao.Alterar(cli); 
           preencherTabela("select cli_codigo,cli_nome,cli_telefone,cli_rg,bainome from cliente inner join bairro on cli_baicodigo = baicodigo order by cli_nome");
           
           jButtonSalvar.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFielCEP.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldTel.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);
        
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!false);
        
        jTextFieldCodCli.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldNome.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFielCEP.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTel.setText("");
        
        }
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag=1;
        jButtonSalvar.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jFormattedTextFielCEP.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldTel.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldCodCli.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldNome.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFielCEP.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTel.setText("");
        
        jTextFieldNome.setRequestFocusEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag=2;
        jButtonSalvar.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jFormattedTextFielCEP.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldTel.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        jButtonSalvar.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFielCEP.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldTel.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);
        
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!false);
        
        cli.setPesquisa(jTextFieldPesquisa.getText());
        BeansClientes cli1 = dao.buscaCliente(cli);
        jTextFieldNome.setText(cli1.getNomeCli());
        jTextFieldCodCli.setText(String.valueOf(cli1.getCodCli()));
        jFormattedTextFieldNasc.setText(cli1.getNasc());
        jFormattedTextFieldRG.setText(cli1.getRg());
        jFormattedTextFieldTel.setText(cli1.getTelefone());
        jTextFieldRua.setText(cli1.getRua());
        jFormattedTextFielCEP.setText(cli1.getCep());
        jTextFieldComplemento.setText(cli1.getComplemento());
        jComboBoxBairro.setSelectedItem(cli1.getNomeBairro());
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta==JOptionPane.YES_OPTION){
        cli.setCodCli(Integer.parseInt(jTextFieldCodCli.getText()));
        dao.Excluir(cli);
        preencherTabela("select cli_codigo,cli_nome,cli_telefone,cli_rg,bainome from cliente inner join bairro on cli_baicodigo = baicodigo order by cli_nome");
        
        jTextFieldCodCli.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldNome.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFielCEP.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTel.setText("");
        
        jButtonSalvar.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFielCEP.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldTel.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);
        
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!false);
        
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        String nome_cliente =""+jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 1);
        conex.getConnection();
        conex.executaSql("select *from cliente where cli_nome= '"+nome_cliente+"'");
        try {
            conex.rs.first();
            jTextFieldCodCli.setText(String.valueOf(conex.rs.getInt("cli_codigo")));
            jTextFieldNome.setText(conex.rs.getString("cli_nome"));
            jFormattedTextFieldRG.setText(conex.rs.getString("cli_rg"));
            jFormattedTextFieldNasc.setText(conex.rs.getString("cli_nasc"));
            jFormattedTextFieldTel.setText(conex.rs.getString("cli_telefone"));
            jTextFieldRua.setText(conex.rs.getString("cli_rua"));
            jTextFieldComplemento.setText(conex.rs.getString("cli_complemento"));
            jFormattedTextFielCEP.setText(conex.rs.getString("cli_cep"));
            ConexaoBD conexPesquisa = new ConexaoBD();
            conexPesquisa.getConnection();
            conexPesquisa.executaSql("select * from bairro where baicodigo = "+conex.rs.getInt("cli_baicodigo"));
            conexPesquisa.rs.first();
            jComboBoxBairro.setSelectedItem(conexPesquisa.rs.getString("bainome"));
            
            conexPesquisa.desconecta();
            
           
        jTextFieldComplemento.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFielCEP.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldTel.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);
        
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!false);
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados"+ex);
        }
        conex.desconecta();
        
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldCodCli.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldNome.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFielCEP.setText("");
        jFormattedTextFieldNasc.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTel.setText("");
        
        jButtonSalvar.setEnabled(!true);
        jTextFieldComplemento.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFielCEP.setEnabled(!true);
        jFormattedTextFieldNasc.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldTel.setEnabled(!true);
        jComboBoxBairro.setEnabled(!true);
        
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBairroActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas  = new String[]{"ID", "Nome","Telefone", "RG", "Rua"};
        conex.getConnection();
        conex.executaSql(Sql);
        
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("cli_codigo"),conex.rs.getString("cli_nome"),conex.rs.getString("cli_telefone"),conex.rs.getString("cli_rg"),conex.rs.getString("bainome")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Busque por outro Cliente para preencher a tabela");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableCliente.setModel(modelo);
        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(23);
        jTableCliente.getColumnModel().getColumn(0).setResizable(false);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableCliente.getColumnModel().getColumn(1).setResizable(false);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableCliente.getColumnModel().getColumn(2).setResizable(false);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableCliente.getColumnModel().getColumn(3).setResizable(false);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(135);
        jTableCliente.getColumnModel().getColumn(4).setResizable(false);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);
        jTableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxBairro;
    private javax.swing.JFormattedTextField jFormattedTextFielCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldCodCli;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconT.png")));
    }
}
