/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansAgenda;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoAgenda;

/**
 *
 * @author Gabriel
 */
public class FormAgendammento extends javax.swing.JFrame {
    
    ConexaoBD conex = new ConexaoBD();
    BeansAgenda agenda = new BeansAgenda();
    
    public FormAgendammento() {
        setIcon();
        initComponents();
        preencherTatuador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonCancelarAge = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTatuador = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextFieldObs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agendamento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 150, 23);

        jButtonFinalizar.setText("Finalizar Agendamento");
        jButtonFinalizar.setEnabled(false);
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizar);
        jButtonFinalizar.setBounds(70, 370, 170, 23);

        jButtonCancelarAge.setText("Cancelar Agendamento");
        jButtonCancelarAge.setEnabled(false);
        jButtonCancelarAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAgeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarAge);
        jButtonCancelarAge.setBounds(290, 370, 170, 23);

        jDateChooser1.setEnabled(false);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(360, 110, 208, 20);

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 120, 40, 14);

        jComboBoxTatuador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTatuador.setEnabled(false);
        getContentPane().add(jComboBoxTatuador);
        jComboBoxTatuador.setBounds(80, 110, 200, 20);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tatuador:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 63, 14);
        getContentPane().add(jTextFieldCliente);
        jTextFieldCliente.setBounds(80, 50, 350, 30);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 47, 20);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar);
        jButtonBuscar.setBounds(440, 50, 120, 30);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 565, 99);

        jTextFieldObs.setEnabled(false);
        getContentPane().add(jTextFieldObs);
        jTextFieldObs.setBounds(10, 280, 565, 82);

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Observações:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 260, 90, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 410);

        setSize(new java.awt.Dimension(608, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void preencherTatuador(){
        conex.getConnection();
        
        conex.executaSql("select *from tatuadores order by nome_tatuador");
        try {
            conex.rs.first();
            jComboBoxTatuador.removeAllItems();
            do{
                jComboBoxTatuador.addItem(conex.rs.getString("nome_tatuador"));
            }while(conex.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher Tatuador"+ex);
        }
        conex.desconecta();
    }
    
    
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        preencherTabela("select cli_codigo,cli_nome,cli_telefone,cli_rg,bainome from cliente inner join bairro on cli_baicodigo = baicodigo where cli_nome like'%"+jTextFieldCliente.getText()+"%'");
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        String nome_cliente =""+jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 1);
        conex.getConnection();
        conex.executaSql("select *from cliente where cli_nome= '"+nome_cliente+"'");
        try {
            conex.rs.first();
            jTextFieldCliente.setText(conex.rs.getString("cli_nome"));
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Erro ao buscar cliente"+ ex);
        }
        conex.desconecta();
        
        jComboBoxTatuador.setEnabled(true);
        jDateChooser1.setEnabled(true);
        jTextFieldObs.setEnabled(true);
        jButtonFinalizar.setEnabled(true);
        jButtonCancelarAge.setEnabled(true);
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        agenda.setNomeCli(jTextFieldCliente.getText());
        agenda.setNomeTatu((String) jComboBoxTatuador.getSelectedItem());
        agenda.setObserva(jTextFieldObs.getText());
        agenda.setData(jDateChooser1.getDate());
        agenda.setStatus("Aberto");
        DaoAgenda dao = new DaoAgenda();
        dao.Salvar(agenda);
        
        dispose();
        jTextFieldCliente.setText("");
        jTextFieldObs.setText("");
        jDateChooser1.setDate(null);
        
        jComboBoxTatuador.setEnabled(!true);
        jDateChooser1.setEnabled(!true);
        jTextFieldObs.setEnabled(!true);
        jButtonFinalizar.setEnabled(!true);
        jButtonCancelarAge.setEnabled(!true);
        
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jButtonCancelarAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAgeActionPerformed
        jTextFieldCliente.setText("");
        jTextFieldObs.setText("");
        jDateChooser1.setDate(null);
        
        jComboBoxTatuador.setEnabled(!true);
        jDateChooser1.setEnabled(!true);
        jTextFieldObs.setEnabled(!true);
        jButtonFinalizar.setEnabled(!true);
        jButtonCancelarAge.setEnabled(!true);
    }//GEN-LAST:event_jButtonCancelarAgeActionPerformed

    
    
    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas  = new String[]{"ID", "Nome","Telefone", "RG", "Rua"};
        conex.getConnection();
        conex.executaSql(Sql);
        
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("cli_codigo"),conex.rs.getString("cli_nome"),conex.rs.getString("cli_telefone"),conex.rs.getString("cli_rg"),conex.rs.getString("bainome")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Busque por outro Cliente para preencher a tabela");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableCliente.setModel(modelo);
        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(23);
        jTableCliente.getColumnModel().getColumn(0).setResizable(false);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableCliente.getColumnModel().getColumn(1).setResizable(false);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableCliente.getColumnModel().getColumn(2).setResizable(false);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableCliente.getColumnModel().getColumn(3).setResizable(false);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(135);
        jTableCliente.getColumnModel().getColumn(4).setResizable(false);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);
        jTableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgendammento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgendammento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgendammento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgendammento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgendammento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelarAge;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JComboBox<String> jComboBoxTatuador;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldObs;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconT.png")));
    }
}
