/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoAgenda;

/**
 *
 * @author Gabriel
 */
public class FormAgendaTatuador extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    DaoAgenda daoAgenda = new DaoAgenda();
    String cod_age;
    String dtHoje;
    String status;
    /**
     * Creates new form FormAgendaTatuador
     */
    public FormAgendaTatuador() {
        setIcon();
        initComponents();
        
        Calendar data = Calendar.getInstance();
        Date d = data.getTime();
        SimpleDateFormat dateFortmat = new  SimpleDateFormat("yyyy/MM/dd");
        dateFortmat.format(d);
        
        
        dtHoje = dateFortmat.format(d);
        status = "Atendimento";
        
        
        preencherTatuador();
        
    }
    
    public void preencherTatuador(){
        conex.getConnection();
        
        conex.executaSql("select *from tatuadores order by nome_tatuador");
        try {
            conex.rs.first();
            jComboBoxTatuador.removeAllItems();
            do{
                jComboBoxTatuador.addItem(conex.rs.getString("nome_tatuador"));
            }while(conex.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher Tatuador"+ex);
        }
        conex.desconecta();
    }
    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas  = new String[]{"ID", "Nome","Data", "Status", "Tatuador"};
        conex.getConnection();
        conex.executaSql(Sql);
        
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("agenda_cod"),conex.rs.getString("cli_nome"),conex.rs.getString("agenda_data"),conex.rs.getString("agenda_status"),conex.rs.getString("nome_tatuador")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Não existe atendimento para este Tatuador");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableAgendaClienteAtender.setModel(modelo);
        jTableAgendaClienteAtender.getColumnModel().getColumn(0).setPreferredWidth(23);
        jTableAgendaClienteAtender.getColumnModel().getColumn(0).setResizable(false);
        jTableAgendaClienteAtender.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableAgendaClienteAtender.getColumnModel().getColumn(1).setResizable(false);
        jTableAgendaClienteAtender.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableAgendaClienteAtender.getColumnModel().getColumn(2).setResizable(false);
        jTableAgendaClienteAtender.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableAgendaClienteAtender.getColumnModel().getColumn(3).setResizable(false);
        jTableAgendaClienteAtender.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTableAgendaClienteAtender.getColumnModel().getColumn(4).setResizable(false);
        jTableAgendaClienteAtender.getTableHeader().setReorderingAllowed(false);
        jTableAgendaClienteAtender.setAutoResizeMode(jTableAgendaClienteAtender.AUTO_RESIZE_OFF);
        jTableAgendaClienteAtender.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAtender = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTatuador = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgendaClienteAtender = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agenda Tatuador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 220, 23);

        jButtonAtender.setText("Atender Cliente");
        jButtonAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtenderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtender);
        jButtonAtender.setBounds(10, 280, 679, 30);

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agendamento de Cliente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 160, 14);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tatuador:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 30, 70, 14);

        jComboBoxTatuador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxTatuador);
        jComboBoxTatuador.setBounds(510, 20, 169, 20);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar);
        jButtonBuscar.setBounds(520, 63, 169, 30);

        jTableAgendaClienteAtender.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAgendaClienteAtender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAgendaClienteAtenderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAgendaClienteAtender);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 679, 165);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background2.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-6, 4, 730, 370);

        setSize(new java.awt.Dimension(741, 379));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        int cod = daoAgenda.BuscarCodTatuador((String) jComboBoxTatuador.getSelectedItem());
        String codigo = String.valueOf(cod);
        preencherTabela("select *from agenda inner join cliente on agenda_codcli=cli_codigo inner join tatuadores on agenda_codtatuador=cod_tatuador where agenda_codtatuador='"+codigo+"' and agenda_data='"+dtHoje+"' and agenda_status='"+status+"'");

        preencherTabela(null);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtenderActionPerformed
        FormAtendimento tela = new FormAtendimento(cod_age);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtenderActionPerformed

    private void jTableAgendaClienteAtenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAgendaClienteAtenderMouseClicked
        cod_age = "" + jTableAgendaClienteAtender.getValueAt(jTableAgendaClienteAtender.getSelectedRow(), 0);
    }//GEN-LAST:event_jTableAgendaClienteAtenderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgendaTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgendaTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgendaTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgendaTatuador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgendaTatuador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtender;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxTatuador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAgendaClienteAtender;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconT.png")));
    }
}
